language: python
python:
  - "2.7"
# command to install dependencies
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install gfortran g++
  - sudo apt-get install python-dev python-pip
  - sudo apt-get install python-virtualenv
  - sudo pip install virtualenvwrapper
  - export WORKON_HOME=$HOME/.virtualenvs
  - export VIRTUALENVWRAPPER_PYTHON=`which python`
  - source /usr/local/bin/virtualenvwrapper.sh
  - pip install virtualenvwrapper
  - mkvirtualenv py27
  - workon py27
  - sudo apt-get install libatlas-base-dev liblapack-dev
  - pip install numpy scipy
  - apt-cache depends python-matplotlib | awk '/Depends:/{print $2}' | xargs dpkg --get-selections
  - apt-get build-dep python-matplotlib
  - pip install matplotlib
  - pip install -e git+https://github.com/ipython/ipython.git#egg=ipython
  - cd ~/.virtualenvs/py27/src/ipython
  - python setupegg.py install
  - pip install nose cython numexpr
  - pip install -e git+https://github.com/wesm/pandas#egg=pandas
install: 
   - "python -c 'import numpy'"
   - "python -c 'import scipy'"
   - "python -c 'import scipy.ndimage'"
   - "pip install -r requirements.txt --use-mirrors"
# command to run tests
script: nosetests
