language: python

python:
  - 2.7
  - 3.3

virtualenv:
  system_site_packages: true

before_install:
 - pip install -q --use-mirrors nose numpy scipy

install:
  - python setup.py install

script: nosetests
