language: python
python:
  - 2.7

matrix:
  include:
  - python: 2.7
    env: NOSE_ARGS="not slow"
  exclude:
  - python: 2.7

virtualenv:
  system_site_packages: true

before_install:
  - ci/before_install.sh

install:
  - pip install nose cython numexpr
  - pip install -e git+https://github.com/pydata/pandas#egg=pandas
  - pip install git+https://github.com/PyTables/PyTables.git@v.3.0.0#egg=tables
  - pip install git+https://github.com/tacaswell/trackpy.git#egg=trackpy
#  - pip install -e svn+http://pylibtiff.googlecode.com/svn/trunk/
  - python setup.py build_ext install
# command to run tests
script: nosetests
