language: python

env:
  - DEPS="python=2.7.7 numpy=1.7.1 scipy=0.13.0 nose matplotlib=1.3 pandas=0.13.0 scikit-image=0.9 pyyaml pytables"
  - DEPS="python=2.7.7 numpy=1.7.1 scipy=0.13.0 nose matplotlib=1.3 pandas=0.13.0 scikit-image=0.9 pyyaml numba=0.11 pytables"
  - DEPS="python=2.7.7 numpy=1.8 scipy nose matplotlib=1.3 pandas=0.13.0 scikit-image=0.10.1 pyyaml numba=0.12 pytables"
  - DEPS="python=2.7.7 numpy=1.8 scipy=0.14.0 nose matplotlib=1.3 pandas=0.13.0 scikit-image=0.10.1 pyyaml numba=0.12.2 pytables"
  - DEPS="python=3.4 numpy=1.8 scipy=0.14.0 nose matplotlib=1.3 pandas=0.14.0 scikit-image=0.10.1 pyyaml pytables"

install:
  - conda create -n testenv --yes $DEPS pip
  - source activate testenv
# TODO Remove these once setup.py handles dependencies correctly.
  - pip install -e svn+http://pylibtiff.googlecode.com/svn/trunk/
  - python setup.py install

before_install:
  - sudo apt-get install libhdf5-serial-dev hdf5-tools
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-2.2.2-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-2.2.2-Linux-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/anaconda/bin:$PATH
  # Learned the hard way: miniconda is not always up-to-date with conda.
  - conda update --yes conda

script: nosetests --nologcapture -a '!slow'
