language: python
python:
  - "2.7"
# command to install dependencies
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install gfortran g++
  - sudo apt-get install python-dev python-pip
  - sudo apt-get install python-virtualenv
  - sudo pip install virtualenvwrapper
  - export WORKON_HOME=$HOME/.virtualenvs
  - export VIRTUALENVWRAPPER_PYTHON=`which python`
  - source /usr/local/bin/virtualenvwrapper.sh
  - pip install virtualenvwrapper
  - mkvirtualenv py27
  - workon py27
  - sudo apt-get install libatlas-base-dev liblapack-dev
install: 
  - pip install numpy
  - pip install scipy
  - pip install matplotlib
  - pip install nose cython numexpr
  - pip install -e git+https://github.com/pydata/pandas#egg=pandas
  - pip install -r requirements.txt --use-mirrors
# command to run tests
script: nosetests
